<ul id="sidebar" class="floating-left">
  <li class="sidebaritem">
    <a class="linkedin" href="https://www.linkedin.com" target="_new">
      <img src="icons/logos/icon.linkedin.svg" alt="LinkedIn"/>
    </a>
  </li>
  <li class="sidebaritem">
    <a class="facebook" href="https://www.facebook.com" target="_new">
      <img src="icons/logos/icon.facebook.svg" alt="Facebook"/>
    </a>
  </li>
  <li class="sidebaritem">
    <a class="youtube" href="https://www.youtube.com" target="_new">
      <img src="icons/logos/icon.youtube.svg" alt="Youtube"/>
    </a>
  </li>
  <li class="sidebaritem">
    <a class="twitter" href="https://twitter.com" target="_new">
      <img src="icons/logos/icon.twitter.svg" alt="Twitter"/>
    </a>
  </li>
  <li class="sidebaritem">
    <a class="instagram" href="https://www.instagram.com" target="_new">
      <img src="icons/logos/icon.instagram.svg" alt="Instagram"/>
    </a>
  </li>
  <li class="sidebaritem">
    <a class="pinterest" href="https://www.pinterest.com" target="_new">
      <img src="icons/logos/icon.pinterest.svg" alt="Pinterest"/>
    </a>
  </li>
  <li class="sidebaritem">
    <a class="whatsapp" href="https://web.whatsapp.com" target="_new">
      <img src="icons/logos/icon.whatsapp.svg" alt="Whatsapp"/>
    </a>
  </li>
  <li class="sidebaritem">
    <a class="telegram" href="https://web.telegram.org" target="_new">
      <img src="icons/logos/icon.telegram.svg" alt="Telegram"/>
    </a>
  </li>
  <li class="sidebaritem">
    <a class="github" href="https://github.com" target="_new">
      <img src="icons/logos/icon.github.svg" alt="Github"/>
    </a>
  </li>
</ul>
