<!DOCTYPE html>
<html lang="en">
  <head>
    <title>A Website ~ Validation</title>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <meta name="format-detection" content="telephone=no"/>
    <link rel="shortcut icon" href="./imgs/starred_32.png" type="image/x-icon"/>
    <link type="text/css" rel="stylesheet" charset="UTF-8" href="./css/styles.css"/>
    <script type="text/javascript" src="./scripts/jquery-3.6.4.js"></script>
  </head>
  <body>
    <h1>Validation</h1>

    <form id="form_validation" method="POST" action="../controllers/validation.php" id="" onSubmit="console.log('test');'">
      <span>Password: </span><input type="text" name="txtf_password"/>
      <br/>
      <span>Repeat: </span><input type="text" name="txtf_password2"/>
      <br/>
      <input type="submit" value="SET PASSWORD"/>
    </form>

    <script type='text/javascript' charset='UTF-8'>
     console.log('document ready');
    </script>
  </body>
</html>
