<!DOCTYPE html>
<html lang="en">
  <head>
    <title>A Website ~ Login</title>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <meta name="format-detection" content="telephone=no"/>
    <link rel="shortcut icon" href="./imgs/starred_32.png" type="image/x-icon"/>
    <link type="text/css" rel="stylesheet" charset="UTF-8" href="./css/styles.css"/>
    <script type="text/javascript" src="./scripts/jquery-3.6.4.js"></script>
  </head>
  <body>
    <h1>LOGIN</h1>

    <form id="loginform" class="memx1" method="POST" action="../controllers/login.php" id="" onSubmit="console.log('test');'">
      <span>Email: </span><input id="userlogin" name="txtf_email" type="text" value="" placeholder="Email Address" alt="Email"/>
      <br/>
      <span>Password: </span><input name="txtf_password" type="password" value="" placeholder="Password" alt="Password"/>
      <br/>
      <input type="submit" value="LOGIN" onclick="console.log('login click registered');" />
    </form>

    <script type='text/javascript' charset='UTF-8'>
     console.log('document ready');
     document.getElementById('userlogin').focus();
    </script>
  </body>
</html>
