<!DOCTYPE html>
<html lang="en">
  <head>
    <title>A Website ~ ERROR #</title>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <meta name="format-detection" content="telephone=no"/>
    <link rel="shortcut icon" href="./imgs/starred_32.png" type="image/x-icon"/>
    <script type="text/javascript" src="./scripts/jquery-3.6.4.js"></script>
    <link type="text/css" rel="stylesheet" charset="UTF-8" href="./css/styles.css"/>
  </head>
  <body>
    <h1>ERROR #</h1>

    <script type='text/javascript' charset='UTF-8'>
     console.log('document ready');
    </script>
  </body>
</html>
