<link type="text/css" rel="stylesheet" media="screen" charset="UTF-8" href="css/slider.css" />
<?php require "frames/frame_slider.phtml"; ?>

<div id="home_wrapper">
  <h1 class="page_title">Home</h1>
  <h2>The First Paragraph!</h2>
  <figure class="contentimg right"><img src="imgs/quote_coffee.png" alt="coffee" /><figcaption>this is a cup of coffee</figcaption></figure><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed iaculis tellus tristique dolor sagittis blandit. Nunc vitae dolor facilisis metus feugiat tempus. Sed ligula massa, suscipit in mollis a, dignissim quis est. Suspendisse ut viverra eros. In et est orci. Donec sollicitudin ultricies justo, volutpat dapibus diam accumsan a. Proin lacus elit, lacinia in pellentesque et, ultricies eu tellus. Aliquam pellentesque mi id metus laoreet ac laoreet dolor dictum. Aenean quis arcu venenatis augue faucibus auctor. In hac habitasse platea dictumst.</p>
  <br/>
  <h2>Paragraph number two</h2>
  <figure class="contentimg left"><img src="imgs/quote_consulting.png" alt="consulting" /><figcaption>this is a notebook</figcaption></figure><p>Duis ipsum mauris, vulputate eget eleifend sit amet, viverra at magna. <a href="https://www.google.com">Google</a> Aliquam vestibulum blandit massa, et ornare libero gravida ut. Cras vehicula, ligula id dictum vestibulum, velit nisi rutrum est, eget tempus lorem urna in eros. Donec consequat, neque eget ornare ullamcorper, eros libero lacinia mi, in tempus odio leo non lorem. Aliquam erat volutpat. Cras consequat metus in lorem semper ac pretium lectus sagittis.</p>
</div>
