<div id="login_wrapper">
  <h1>Login</h1>
  <p>Please enter your credentials.</p>
  <form id="login_form" method="POST" action="index.php?url=loginform" onSubmit="console.log('test');'">
    <input id="username" type="text" placeholder="Your User Name:" name="name" value="<?php echo $_GET['name']; ?>" /><br/>
    <input id="userpass" type="text" placeholder="Your Password:" name="email" value="<?php echo $_GET['email']; ?>" /><br/>
    <p class="recovery_note">Forgot your password? Start recovery process <a href="?url=recovery">here</a>.</p>
    <br/>
    <input type="submit" value="LOGIN"><br/>
  </form>
  <script>document.getElementById('username').focus();</script>
</div>
